application:
  security:
    jwt:
      secret-key: "secretHere"
      expiration-time-in-min: 30

spring:
  application:
    group: occurrence
    name: api
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://mongodb:mongodb@localhost:27017/mongodb
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: WARN
    br.com.occurrence: INFO

springdoc:
  swagger-ui:
    path: /swagger